name: docker

on:
  push:
    paths-ignore:
      - ".github/**"
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  docker-build-push:
    concurrency: "build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: metisdao
          password: ${{ secrets.METIS_DOCKER_ACCESS_KEY  }}

      - name: Docker meta
        id: docker-meta-keepalive
        uses: docker/metadata-action@v5
        with:
          images: metisdao/metis-keepalive

      - name: Build and push
        uses: docker/build-push-action@v6
        timeout-minutes: 10
        with:
          push: true
          tags: ${{ steps.docker-meta-keepalive.outputs.tags }}
          target: keepalive
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Docker meta for metis-healthy
        id: docker-meta-healthy
        uses: docker/metadata-action@v5
        with:
          images: metisdao/metis-healthy

      - name: Build and push
        uses: docker/build-push-action@v6
        timeout-minutes: 10
        with:
          push: true
          target: healthy
          tags: ${{ steps.docker-meta-healthy.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
